export default function Head() {
  return (
    <>
      <title>SimRail Info</title>
      <link rel="shortcut icon" href="/logo_64.png" type="image/x-icon" />
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      
    </>
  )
}
